### ISSUE TITLE
Running in a directory not set up for React Native crashes

### ISSUE THREAD

**Issue by DavidPotter** [peggyrayzis/react-native-create-bridge#16]
When running the tool in a directory that does not contain a React Native project produces the following results:
```
$ create-bridge 
module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/dpotter/package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-create-bridge/build/file-operations.js:60:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by peggyrayzis** [comment]
Hi David! Thanks for reporting. You do need a `package.json` in order for this module to work. What happens after you create one with `yarn init` or `npm init`?

**Comment by DavidPotter** [comment]
After creating a new directory and executing `yarn init`, then running `create-bridge` with default parameters, I get the following error:

```
[11:29:04] dpotter@dpotter-mac:~/src/prototyping/bar > create-bridge 
? What is your bridge module called? ExampleBridge
? What OS & languages would you like to support? (Press <space> to select, <a> to toggle all, <i> to inverse selection)Android/Java, iOS/Objective-C
? What directory should we deliver your JS files to? .
✖ Oh no! 💩  Something went wrong with creating your bridge module.
Please report any errors here: https://github.com/peggyrayzis/react-native-create-bridge/issues

Error: Error: ENOENT: no such file or directory, open '/Users/dpotter/src/prototyping/tableau-mobile/bar/ios/ExampleBridge.h'
```

Could you enumerate these steps in the README for folks like me that are new to React Native?
