### ISSUE TITLE
Semver error?

### ISSUE THREAD

**Issue by ramubhai** [peggyrayzis/react-native-create-bridge#36]
### Dev setup:
- `react-native-create-bridge` version:
- `react-native` version: 0.48.4

### I am using create-bridge in a:

- [ ] standalone library
- [x] existing React Native project

### What you did:
create-bridge followed by providing all the inputs. 

### What happened:

create-bridge
? What is your bridge module called? react-native-google-cast-v3
? What type of bridge would you like to create? (Press <space> to select, <a> to toggle all, <i> to inverse selection)Native Module, Native UI Component
? What OS & languages would you like to support? (Press <space> to select, <a> to toggle all, <i> to inverse selection)Android/Java, iOS/Objective-C
? What directory should we deliver your JS files to? bridgecast
[readAndWriteFiles]  Error: Invalid argument not valid semver
    at validate (C:\Users\ram\AppData\Roaming\npm\node_modules\react-native-create-bridge\node_modules\compare-versions\index.js:32:19)
    at Array.forEach (native)
    at compareVersions (C:\Users\ram\AppData\Roaming\npm\node_modules\react-native-create-bridge\node_modules\compare-versions\index.js:37:18)
    at parseFile (C:\Users\ram\AppData\Roaming\npm\node_modules\react-native-create-bridge\build\file-operations.js:107:50)
    at _callee3$ (C:\Users\ram\AppData\Roaming\npm\node_modules\react-native-create-bridge\build\file-operations.js:148:28)
    at tryCatch (C:\Users\ram\AppData\Roaming\npm\node_modules\react-native-create-bridge\node_modules\regenerator-runtime\runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\ram\AppData\Roaming\npm\node_modules\react-native-create-bridge\node_modules\regenerator-runtime\runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\ram\AppData\Roaming\npm\node_modules\react-native-create-bridge\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\ram\AppData\Roaming\npm\node_modules\react-native-create-bridge\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\ram\AppData\Roaming\npm\node_modules\react-native-create-bridge\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
√ Your bridge module was successfully created! 🎉

I am new to react-native & nodejs so pardon if I am missing something silly. It says module creation was successful, than why the error messages.?

**Comment by ramubhai** [comment]
Checked, error happens only when we select Andorid/Java. Not happens when only iOS is selected.
Further can reproduce on windows mac both.

**Comment by jarretmoses** [comment]
@ramubhai could you possibly create a reproduction repo? I tried to reproduce on RN 48.4 and 49.0 but am not seeing the error.

**Comment by ramubhai** [comment]
I created a fresh project using react-native init and it worked fine. So there must be some issues with my specific projects. I will updated once I find out what worked.

**Comment by ramubhai** [comment]
Ok. I tracked down the error to versioning style in root level project.json of react-native project. 
Following works correctly.
"dependencies": {
		"react": "16.0.0-beta.5",
		"react-native": "0.49.3"
	},

but following fails with an error regarding semver.

"dependencies": {
		"react": "16.0.0-beta.5",
		"react-native": "^0.49.3"
	},

Adding any new dependency using "react-native link" seems to be prefixing the "^" symbol before version. In my case, even the react-native dependency itself had "v0.48.4". 

I have put a reproduction repo at following address. Hope you can workout a fix. 
https://github.com/ramubhai/DEBUG_BRIDGE

Thanks for all the hard work and patience. :)

**Comment by jarretmoses** [comment]
@ramubhai thanks for investigating this. I’ve opened a PR to resolve this issue.

**Comment by marchon** [comment]
Thank you for sorting this out!!! Much appreciated. :)

**Comment by jarretmoses** [comment]
Getting this package going again. Stay tuned for some updates here.

**Comment by DanielBoening** [comment]
Today I encountered the same error. Any reasons the open PR is not merged?

**Comment by jarretmoses** [comment]
@DanielBoening I will work on having it in, in the next couple days.

**Comment by DanielBoening** [comment]
Awsome! Thank you
